name: Approval

on:
  repository_dispatch:
    types: [approve-deployment]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Approval
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const { data } = await octokit.request("GET /repos/{owner}/{repo}/pulls", {
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const pendingReview = data.find(pr => pr.head.ref === "${{ github.event.client_payload.ref }}" && pr.state === "open");

            if (pendingReview) {
              console.log(`Found PR for ${pendingReview.head.ref}, waiting for approval.`);
              await octokit.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pendingReview.number,
                event: "APPROVE"
              });
              console.log("PR approved. Proceeding with deployment.");
            } else {
              throw new Error("No open pull request found for the branch.");
            }
