name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: approve-deployment
          client-payload: '{"ref": "${{ github.ref }}"}'
    
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: fuka-chan-seperate-cicd
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: . # Deploy the entire project directory
