name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: ./
      - name: List files after downloading artifact
        run: ls -R ./
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: fuka-chan-seperate-cicd
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./ # Adjust this if necessary

  manual-approval:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        uses: hmarr/approve-action@v2
        with:
          custom-message: 'Approve deployment to production?'
          reviewers: 'anaitik'
