name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build # Ensure this step generates your build artifacts
      - name: List files before uploading artifact
        run: ls -R ./
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./ # Adjust this to the path of your build artifacts if different
